FROM gcc:13-bookworm as builder

RUN apt update && \
    apt install -y  cmake libasio-dev libspdlog-dev && \
    rm -rf /var/lib/apt/lists/*

WORKDIR /app
COPY . /app
RUN cmake -S . -B build && \
    cmake --build build --target server -j 6

#FROM debian:bookworm-slim as runtime
#WORKDIR /app
#COPY --from=builder /app/build/server .
#CMD ["./server"]


