FROM gcc:13.2-bookworm
LABEL authors="clonemasteruwu"

RUN apt-get update && \
    apt-get install -y cmake libboost-context-dev && \
    rm -rf /var/lib/apt/lists/*
RUN curl https://raw.githubusercontent.com/matt-42/lithium/master/install.sh | bash -s - /usr/local

WORKDIR /app
COPY . /app
RUN mkdir build && \
    cd build && \
    cmake .. && \
    cmake --build . --target server -j 6