FROM gcc:13-bookworm
LABEL authors="clonemasteruwu"

RUN apt update && \
    apt install -y cmake libgdal-dev libspdlog-dev libboost-program-options-dev && \
    rm -rf /var/lib/apt/lists/*

WORKDIR /app
COPY . /app
RUN mkdir build && \
    cd build && \
    cmake .. && \
    cmake --build . --target analytic -j 6